### ISSUE TITLE
implement regex cleanup support

### ISSUE THREAD

**Issue by andykais** [andykais/scrape-pages#13]
inputs, downloads, & parses all have an option for regexCleanup. This issue is to implement that feature.

```ts
type RegexRemove = string
type RegexReplace = {
  selector: string
  replacer: string
}
type RegexCleanup = RegexRemove | RegexReplace
```

```yml
define:
  api:
    download:
      urlTemplate: ...
      # find regex and replace with ''
      regexCleanup: "var json="
```
a string value becomes the long version: `{ selector: string, replacer: '' }`
